import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";
import { MuiThemeProvider } from "@/providers/MuiThemeProvider";
import { SnackbarProvider } from "@/providers/SnackbarProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ChatGPT",
  description:
    "Generated by create next appChat Generative Pre-trained Transformer",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MuiThemeProvider>
          <SnackbarProvider>{children}</SnackbarProvider>
        </MuiThemeProvider>
      </body>
    </html>
  );
}
